<li class="file-widget">
  <div class="border-top"></div>
  <div class="container">
    <div class="content">
      <img class="icon" src="/site/mime/<?php echo $this->icon ?>-24.png">
      <span class="title">
        <a href="<?php echo $this->url?>">
          <?php echo $this->title?>
        </a>
      </span>
      <div class="expando" style="display:none;"></div>
      <div class="line"></div>
      <div class="fileinfo" style="display:none;">
        <div class="filename">
          <?php echo $this->translate('file.name') . ': ' . $this->filename?>
        </div>
        <div class="filesize">
          <?php echo $this->translate('file.size') . ': ' . $this->formatFilesize($this->size)?>
        </div>
        <div class="filedate">
          <?php echo $this->translate('file.date') . ': ' . $this->date?>
        </div>
      </div>
    </div>
  </div>
  <div class="border-bottom"></div>
</li>