<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Admin</title>
    <link rel="stylesheet" href="/admin/src/app/resources/app.css">
  </head>
  <body class="claro">
    <script>
      var dojoConfig = {
        async: 1,
        tlmSiblingOfDojo: 0,
        parseOnLoad: false,
        isDebug: 1,
        locale: "en",
        //cacheBust: true
      }
    </script>
    <script src="/admin/src/dojo/dojo.js" defer></script>
    <script src="/admin/src/app/run.js" defer></script>
  </body>
</html>