<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Admin</title>
    <link rel="stylesheet" href="/admin/dist/app/resources/app.css">
  </head>
  <body class="claro">
    <script
        src="/admin/dist/dojo/dojo.js"
        data-dojo-config="
          async: 1,
          tlmSiblingOfDojo: 1,
          isDebug: 0,
          locale: 'en',
          packages: ['dojo', 'dojox', 'dijit', 'app'],
          baseUrl: 'admin/dist',
          deps: ['app/main']
        ">
    </script>
  </body>
</html>